### ISSUE TITLE
Starter Apini colonists have a helmet

### ISSUE THREAD

**Issue by AerosAtar** [Jack7D1/Rimworld-Apini#122]
Apini starter colonists come with an equipped helmet and a few meals. They should only start with the same gear as other starter colonists (clothing).

**Comment by Jack7D1** [comment]
It's intentional that they start eith honeyglass helmets, however it may be best balance wise to remove it...

**Comment by AerosAtar** [comment]
Apologies, I think my initial report was worded a little bluntly. Yes, what I meant is that, balance-wise, I believe it would be preferable for them to only have the same gear as regular (human) starting colonists.

**Comment by Jack7D1** [comment]
Yeah no biggie! It's on the funny list, just awaiting the freeze to end.
