### ISSUE TITLE
Patch w/ Rimbees Missing costList tags.

### ISSUE THREAD

**Issue by chrispikula** [Jack7D1/Rimworld-Apini#124]
https://github.com/Jack7D1/Rimworld-Apini/blob/ada0e2f6f061336168a687850a4e5638606dd4e8/1.3/Patched/P_Rimbees/Patches/Patch_Rimbees.xml#L243-L246

Should be

      <xpath>Defs/ThingDef[defName = "MeatHoneyVat"]/costList/ApiniWax</xpath>
      <value>
	      <costList>
		      <RB_Beeswax>30</RB_Beeswax>
	      </costList>
      </value>

Yes?

I'd make a fork, but that's a lot of work.  :-p

**Comment by Jack7D1** [comment]
Pah! Something always slips through.. Hotfixing now!
