### ISSUE TITLE
Goodwill with the empire doesn't change

### ISSUE THREAD

**Issue by Techsss** [Jack7D1/Rimworld-Apini#17]
This is after the fix that was meant to patch the bug where you remain hostile to the empire.

It seems this patch did however not take effect as even after the bug completing a question that was meant to give Goodwill +80 and other items, the only thing that would come out of it was the items and not the goodwill as the empire would still be at goodwill - 100 and hostile

**Comment by Jack7D1** [comment]
This bug seems to be save specific and can't be reproduced. #15 causes saves to start at neutral relations to empire now. It's possible the bug will go away with the next quest.
