### ISSUE TITLE
Naked Brutality Azuri mode

### ISSUE THREAD

**Issue by Twitchapher** [Jack7D1/Rimworld-Apini#45]
There be naked brutality apini mode, no dumb wasp naked brutality mode. Dumb wasp wish to prove wasp is smart and don't need no friends. Wasp strong. Wasp take over planet. Wasp make home out out of bones of enemies and pretty skull hats. Antenna go threw eye sockets of skull, very fashionable.

**Comment by Jack7D1** [comment]
A good idea! would be even more challenging than the Apini version.
