### ISSUE TITLE
Installing Crusher Mandibles removed left and right mandibles, reducing talking to 0

### ISSUE THREAD

**Issue by JulianSkies** [Jack7D1/Rimworld-Apini#47]
Azuri patient, selected the Install Crusher Mandibles surgery
After surgery I noticed the patient had 0 Talking, verified and the popup showed the following culprits:
Crusher Mandibles
Anesthetic (Woozy)
Dementia
Thorax: 65/75
Left Mandible: 0/15
Right Mandible: 0/15
Consciousness: 69%
I also have Medical System Expansion 2, but MSE2 should skip over any surgery it doesn't identify, such as the mandibles.

**Comment by Jack7D1** [comment]
Hey! Thanks a ton for bothering to make an git issue!
This seems really silly to have missed, it'll be fixed!

**Comment by Jack7D1** [comment]
MSE2 tested and confirmed to have no incompatibilities or conflicts with any of Apinis function.

**Comment by Jack7D1** [comment]
This issue only exists with MSE2 installed, a patch will be made.
