### ISSUE TITLE
Setting outfits causes all bees to prefer being nude

### ISSUE THREAD

**Issue by AemiDaniels** [Jack7D1/Rimworld-Apini#48]
I had set up outfit rules specifically to stop my buzzing colonists from wearing tainted stuff or anything below 65% durability. They all ran to the clothing storage and started stripping. I figured they were changing clothes since the vast majority of them were wearing tainted outfits. However, they all left naked. I can force them to wear stuff but for the most part they just refuse to wear any of the new aprons and ruffs i made them. The soldiers won't even touch the helmets or utility stuff i set aside for them. I know they CAN wear them as I see visiting traders sometimes have war outfits on, but my colonists seem to have the attitude of "i wear anything i want without restriction or ill be naked."

**Comment by AemiDaniels** [comment]
nevermind. im an idiot and had the quality set backwards. my bad.

**Comment by Jack7D1** [comment]
pff is ok. Thanks for making an issue thought!
