### ISSUE TITLE
Cant equip sheilds. 

### ISSUE THREAD

**Issue by PhoenixWolf0** [Jack7D1/Rimworld-Apini#50]
Unable to equip shields from Vanilla Factions Expanded - Medieval. 
https://gyazo.com/e8c6a11d672ccc6cb7bc1c991eddeb78

**Comment by Jack7D1** [comment]
Save file: https://cdn.discordapp.com/attachments/282995683609280512/782074235229044776/Beep_-_Copy.zip

**Comment by Jack7D1** [comment]
Hi! After some really big troubles with this issue could you please narrow down the mods that could possibly be causing this issue? The sheer amount of mods is making this an effectively impossible task, see #54!

**Comment by PhoenixWolf0** [comment]
I believe it's just vanilla expanded medieval shields not being whitelisted. If it's not this ill be able to check mods on Wednesday for you. School is putting a lot of work. 
https://steamcommunity.com/sharedfiles/filedetails/?id=2023513450&searchtext=vanilla+factions+expanded

**Comment by PhoenixWolf0** [comment]
It's working now I think it's now a problem with simple sidearms now. Thought I did see that riot shields from Vanilla expanded insectoids didn't work
![image](https://user-images.githubusercontent.com/75148605/100695686-58ce0480-3357-11eb-8df0-4f3d0a18e382.png)
Mod: https://steamcommunity.com/sharedfiles/filedetails/?id=2149755445

Sorry for waisting your time like this ill do some more testing before I send another report here.
