### ISSUE TITLE
FEATURE: Antibiotics and mead from honey

### ISSUE THREAD

**Issue by AemiDaniels** [Jack7D1/Rimworld-Apini#52]
Sort of like how herbal medicine is a slightly less effective but much easier to mass manufacture medicine, honey made antibiotics could be mass-manufactured at a drug lab but be a little less effective at slowing down infection/disease spreads. It would have the benefit of being non-addictive though.

Also, I know there are other alcohol mods out there, but being able to run our excess honey through the brewery and fermenting vats to make honey mead would be cool. Or even being able to use it as an animal byproduct ingredient in cooking. Just something to give it a little more use after you are done covering your whole base in the stuff.

**Comment by Jack7D1** [comment]
Right now there is royal jelly for a hefty immune boost!
But it's locked behind insect jelly. I like he idea of being able to process excess honey into medicines in the late game, as often in the late game you have far too much honey.

**Comment by PhoenixWolf0** [comment]
A way to turn honey into power would be cool and a good way to sink a lot of honey you don't need.

**Comment by Jack7D1** [comment]
This feature will need some artwork and other features but otherwise I think this is a great thing to add to the mod! Will be added *someday* probably*

**Comment by Jack7D1** [comment]
I was waiting on this to use vanilla expanded viking's meads, however it turns out it won't really work...
This is all going to be done independant of VE stuff, and honey generator really does seem like a neat idea :>
