### ISSUE TITLE
disfigured bug.

### ISSUE THREAD

**Issue by PhoenixWolf0** [Jack7D1/Rimworld-Apini#53]
Disfigured social seems to appear on wing injurys. I haven't seen it appearing for any other injury.
![image](https://user-images.githubusercontent.com/75148605/100564048-7e8ad900-3285-11eb-9c73-930f2e65467f.png)
![image](https://user-images.githubusercontent.com/75148605/100564055-80ed3300-3285-11eb-8bb6-3833377cae5a.png)
[Beep.zip](https://github.com/Jack7D1/Rimworld-Apini/files/5613548/Beep.zip)

**Comment by Jack7D1** [comment]
Hi! Could you take a look at the comment on #50?

**Comment by PhoenixWolf0** [comment]
I did for you turns out it was me being retarded I'm sorry again.
I checked this and this is just a base problem. I checked with only this active.

**Comment by Jack7D1** [comment]
Hey it's ok! thanks for telling me!
