### ISSUE TITLE
Colonists getting stuck trying to pick up honey

### ISSUE THREAD

**Issue by AemiDaniels** [Jack7D1/Rimworld-Apini#55]
Every now and then, a colonist will go to pick up some honey, immediately drop it, and try to pick it up again. This leads to them essentially kicking the honey back and forth like a bored kid with a soccer ball. They will not do anything else unless forced to when they are stuck like this. The weird glitch had gone away for a while but now that i started up a new colony, EVERYONE is doing it. The issue seems to only be when they try to put it in their inventory and i am not sure how to prevent that.

**Comment by Jack7D1** [comment]
interesting, this bug seems to have resurfaced #18
