### ISSUE TITLE
Bee colonists standing around doing apparently nothing

### ISSUE THREAD

**Issue by AemiDaniels** [Jack7D1/Rimworld-Apini#56]
I swear I am finding all the bugs with my bugs >_<
If there is nothing overly pressing for my apini to do, they just sorta stand there. they will talk to anyone who comes by but they won't move unless you make them, and then after they complete the forced task they go back to standing perfectly still until their needs drop enough to force action or a pressing job shows up. Lather, rinse, repeat. They seem to go back to normal after sleeping, but it will happen again at random times.

**Comment by Jack7D1** [comment]
Hi! thanks for making a bug report! Events like these are usually directly paired with errors! Could you follow the procedure in #54 and provide more info? Thanks!

**Comment by AemiDaniels** [comment]
does it need to be a save file with just the apini mod running?

**Comment by Jack7D1** [comment]
If it's only Apini then ye! But the general gist is no more than 12 other non-apini mods (not including dependencies).

**Comment by AemiDaniels** [comment]
ok well i have WAY too many mods running so im not sure if i can get the save file. 
its so sporadic that i am not sure if the glitch is fixed or if im just having a good streak without it happening o_o
ill try running a save with just my bees but i make no guarantees.
