### ISSUE TITLE
Anima Tree not working for hive backstorys. 

### ISSUE THREAD

**Issue by PhoenixWolf0** [Jack7D1/Rimworld-Apini#57]
Since bees start as tribals I think it would make sense for them to also be able to get psylinks from the tree as well. 
![image](https://user-images.githubusercontent.com/75148605/101288170-b7154000-37ba-11eb-9171-0401d5d9d1aa.png)
![image](https://user-images.githubusercontent.com/75148605/101288172-ba103080-37ba-11eb-9250-4d61cb9c4351.png)
[Hive8.zip](https://github.com/Jack7D1/Rimworld-Apini/files/5649280/Hive8.zip)

**Comment by Jack7D1** [comment]
A good idea! This is more of a feature suggestion but definitely counts as an oversight. Will add!

**Comment by Jack7D1** [comment]
I've been picking away at this for a while and I've not been able to crack it really. I'm not able to determine how the Natural meditation focus is assigned to Tribals. Perhaps once a good decompile of Royalty comes out this can finally be fixed.

**Comment by Jack7D1** [comment]
Thanks a TON to Julian Skies for helping with this! 
![image](https://user-images.githubusercontent.com/59462654/114325683-65c9e400-9aff-11eb-81d0-ac4ae3487b55.png)
