### ISSUE TITLE
Azuri raids too powerful

### ISSUE THREAD

**Issue by commanderdarkkirby** [Jack7D1/Rimworld-Apini#58]
this race could REALLY use some armor because this race kind of sucks and are really bad at combat because the only armor they can even wear is a flak vest. not to mention that the azuri, with a high melee stat, goes down way too easily so its not really worth using them for melee purposes when you recruit one. oh and speaking of azuri...maybe also tone down the amount of azuri's that show up in a group durring raids or when attacking their settlements cause it seems unbeatable without op equipment. last time i had like over 100 of them raid my settlement somewhere around mid game. and that was on adventure story, which i assume is suppose to be the normal mode of the game.

**Comment by Jack7D1** [comment]
Hi! Kind need more information.
What storyteller were you using? What was the wealth of your colony?
The Azuri raid builder prioritizes sheer numbers over gear but you should never be seeing much more than you would with tribals. It's likely some other mod is causing this or you had a really high wealth.
Would you mind including information listed in #54 ?

**Comment by commanderdarkkirby** [comment]
well i don't exactly remember the wealth i had last time since i deleted the save file as i beat the game but, i was around mid game and the story teller i was using was Perry Persistent who makes events and quests happen more often and lets you have double the population. i think i had like 18 or 19 pawns (including androids), or 28 if you count the robots from rimsec but i made it so they don't count towards having a pawn. i also set the difficulty to adventure story since i had a pretty good defence. and then that raid happened and over 100 of those azruis raided my settlement and destroyed me, forcing me to reload a save because it was so unfair.

**Comment by commanderdarkkirby** [comment]
ok but really, this race could really use some armor and extra clothing that this race can wear. honestly, they are kind of boring and kind of suck if the only other clothing that they can wear is a flak vest. give them more variety on what they can wear. what if people decide to do a playthrough of only or mostly playing as this race? there is barely anything that they can do against raids if this race can't even wear decent armor later on in the game, besides relying on turrets and traps. but what about when they want to raid other settlements? oh and make them be able to wear scarves, why can't they wear something that just goes around their neck? i don't see why they shouldn't be able to wear them.

**Comment by commanderdarkkirby** [comment]
ok...wow i really went off topic there...
