### ISSUE TITLE
make azuri not permanently hostile when choosing the azuri scenario

### ISSUE THREAD

**Issue by commanderdarkkirby** [Jack7D1/Rimworld-Apini#59]
make it so that the azuri faction is not permanently hostile when you choose the azuri scenario. why would they be forever hostile to their own kind? it doesn't make any sense.

**Comment by Jack7D1** [comment]
While I agree this should be the case, faction defs are pretty clunky, and I have to choose between everyone being able to ally with Azuri, or Azuri always being permanently hostile.

**Comment by commanderdarkkirby** [comment]
but you made the other race permanently hostile when you choose that scenario. does that work differently?

**Comment by Jack7D1** [comment]
The uh, Azuri faction and player Azuri faction are still separate

**Comment by commanderdarkkirby** [comment]
oh...so there is nothing you can do to make the azuri none hostile when you choose that one scenario?
