### ISSUE TITLE
Fix apitech table sprites

### ISSUE THREAD

**Issue by Jack7D1** [Jack7D1/Rimworld-Apini#61]
![image](https://user-images.githubusercontent.com/59462654/105386808-d9d0ac00-5be2-11eb-82d2-c91cf6a19c45.png)
Masking is done poorly on the stuffed apitech tables

**Comment by Jack7D1** [comment]
Since I lack spriting experience this may not be fixed for a while.

**Comment by AluminumAlman** [comment]
I'd suggest to make them non-stuffable since most other production tables aren't stuffable.

**Comment by Jack7D1** [comment]
You know, thats a good idea
