### ISSUE TITLE
Clothing White List Errors

### ISSUE THREAD

**Issue by BlueTressym** [Jack7D1/Rimworld-Apini#64]
Hi.  Using this mod, I get a long list of red errors relating to the clothing whitelist.  Poking around with the tiny bit of knowledge I have showed that it's because the whitelist contains a large number of clothing from  mods, which is great - except that if the mods aren't loaded, it throws all those errors.  Could you get it to do a check for the mods before it compiles the list?  I know that's a thing but I don't know enough to actually do it.  

I've temp fixed it by creating a local copy of the mod and deleting those items from the whitelist but obviously that's not really a solution, especially if I add any of the mods and then have to add the items back in.    

I'm happy to supply a log if you'd like.

**Comment by Jack7D1** [comment]
Hi! This is an old error that was previously fixed, are you using the latest version of https://steamcommunity.com/sharedfiles/filedetails/?id=2204437968 ?

**Comment by BlueTressym** [comment]
I thought I was; I'll go and poke it some more.

**Comment by BlueTressym** [comment]
Yup, the errors have disappeared.  Sorry to have bothered you.

**Comment by Jack7D1** [comment]
pff, is no biggie! Thanks for making an issue though!
