### ISSUE TITLE
constantly getting hints regarding honey making

### ISSUE THREAD

**Issue by commanderdarkkirby** [Jack7D1/Rimworld-Apini#73]
so, i keep getting these hints about honey making like as if the game hasn't already taught me. i don't know what causes it, it seems to be random. but i think it happens every time when i have a azuri or apini as a new colonist.

**Comment by Jack7D1** [comment]
Thanks for making an issue for this! Could you share your save file in accordance with #54 ?

**Comment by Jack7D1** [comment]
helo?

**Comment by commanderdarkkirby** [comment]
oh, sorry for the late response, i forgot to check in on the reply. and uhh...the save? i don't have it anymore, oops...but its easy to replicate though, it happens whenever i encounter a apini or azuri, usually when they become my colonist.

**Comment by Jack7D1** [comment]
Sure! That's ok! Just needed something to work off of in terms of replication. I'll take a look at it then
