### ISSUE TITLE
Azuri can get the "Wasp Wannabee" trait

### ISSUE THREAD

**Issue by Superyodeler** [Jack7D1/Rimworld-Apini#75]
Ran into a couple of raiding Azuri with the "Wasp Wannabee" trait.

They're not wannabees, they're the real thing!

**Comment by Jack7D1** [comment]
Pffff

**Comment by Jack7D1** [comment]
I think when I merged the two race restrictions I might have accidentally deleted the trait restrictions, heck.

**Comment by Jack7D1** [comment]
Turns out it will not be so simple
