### ISSUE TITLE
Transport pod crash generates bee-human hybrids

### ISSUE THREAD

**Issue by Jack7D1** [Jack7D1/Rimworld-Apini#87]
The transport pod crash event generates weird bee-human hybrids with Apini backstories and antennae, but with a human body and name.

**Comment by Sparrowbird611** [comment]
I believe I also received one of these from a quest where I had to take care of another facton's visitor.

**Comment by Jack7D1** [comment]
Hmm, maybe it's from EventGenerator then

**Comment by Jack7D1** [comment]
It looks to be that this bug is more vanilla engrained.
Likely the same situation as this https://github.com/RimWorld-CCL-Reborn/AlienRaces/issues/22

**Comment by Jack7D1** [comment]
There's a good chance that 1.3 may fix this bug 🐛

**Comment by Jack7D1** [comment]
This was indeed fixed in the 1.3 update, closing.
