### ISSUE TITLE
Apini/Azuri Settlements absent from World Generation Settings (Minor)

### ISSUE THREAD

**Issue by Rayllumen** [Jack7D1/Rimworld-Apini#97]
In the world generation settings when you start a new game, There is a menu that allows you to select how many distinct factions inhabit the rimworld. Apini hives and Azuri swarms both are absent from this list, Despite one of each spawning regardless of settings.

This has the potential to be borderline negligible, But since Rimworld explicitly states that there can be gameplay issues above 11 factions; It would be safe to have it at Minor at most.
![Example](https://user-images.githubusercontent.com/87831960/126704219-cd760458-be6e-42b3-9fb0-645e69588598.png)

**Comment by Jack7D1** [comment]
Thanks for putting this on the github!
